import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import styles from '../styles/Home.module.css'
import Three from '@/components/Three'

const Model2: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Underwater 3D Image Exibition</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Three gltfPath={'scene2-meshopt'} />
        <div style={{ position: 'fixed', top: 40, right: 40, cursor: 'pointer' }}>
          <Link href='/'>シーン切り替え</Link>
        </div>
      </main>
    </div>
  )
}

export default Model2
